apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubecost
  namespace: kubecost
  labels:
    app: kubecost
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cost-analyzer
  endpoints:
  - port: http
    interval: 60s
    path: /metrics