apiVersion: v1
kind: ServiceAccount
metadata:
  name: emr-containers-sa-spark-driver
  namespace: emr-fraud-detection
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::368083780519:role/fraud-detection-emr-eks-emr-execution-20250806151622744200000001
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: emr-containers-sa-spark-executor
  namespace: emr-fraud-detection
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::368083780519:role/fraud-detection-emr-eks-emr-execution-20250806151622744200000001