apiVersion: v1
kind: Pod
spec:
  nodeSelector:
    karpenter.sh/nodepool: spark-gpu-rapids
    nvidia.com/gpu: "true"
  tolerations:
  - key: "nvidia.com/gpu"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
  - key: "karpenter.sh/unschedulable"
    operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: spark-kubernetes-executor
    resources:
      requests:
        cpu: "4"
        memory: "8Gi"
        nvidia.com/gpu: "1"
      limits:
        cpu: "8"
        memory: "16Gi"
        nvidia.com/gpu: "1"