apiVersion: v1
kind: Pod
spec:
  tolerations:
  - key: nvidia.com/gpu
    operator: Exists
    effect: NoSchedule
  nodeSelector:
    NodeGroupType: spark-executor-gpu-karpenter
  containers:
  - name: spark-kubernetes-executor
    resources:
      limits:
        nvidia.com/gpu: 1
        memory: 32Gi
        cpu: 4
      requests:
        nvidia.com/gpu: 1
        memory: 30Gi
        cpu: 4
    env:
    - name: NVIDIA_VISIBLE_DEVICES
      value: "all"
    - name: NVIDIA_DRIVER_CAPABILITIES
      value: "compute,utility"